### PR TITLE
Return date of cached response

### PR DESCRIPTION
**Pull request by scraperdragon**
I'm in a position where I'm wanting to be able to know how stale a cached item is: I don't know whether this is a pull request you'd be interested in including or not.

Obviously `cache_date` needs documenting before being accepted; I'm also not certain about the name of the attribute itself.

Any thoughts?

### CODE REVIEW

**Comment by solehill** [comment]
I would be very interested in seeing this included. Any progress? Can I do something to make it happen?

**Comment by libbkmz** [comment]
Are there any plans to merge this PR into master? It would be great to be able to see the time of the original request.

**Comment by jayvdb** [comment]
@scraperdragon, would you be able to rebase this to fix the merge conflicts?

**Comment by JWCook** [comment]
Closing this PR for now, since it has merge conflicts.

If @scraperdragon or anyone else would still like this change added, please submit a new PR, and I'll be happy to review and merge.

**Comment by JWCook** [comment]
Fyi, this has been added as `CachedResponse.created_at`.

**Pull request closed without merging**
