### PR TITLE
Refactor CachedSession to be usable as a mixin class

### PR DESCRIPTION
**Pull request by JWCook**
Closes:
* #158 
* #163
* #149 
* #146
* #144  
* #87

Related changes:
* Add sanity checks to get_cache, clear, and remove_expired_responses to make sure requests-cache is installed before calling CachedSession methods

## Example with requests-html (#149)
```python
import requests
from requests_cache import CacheMixin, install_cache
from requests_html import HTMLSession

class CachedHTMLSession(CacheMixin, HTMLSession):
    """Session with features from both CachedSession and HTMLSession"""

session = CachedHTMLSession()
r = session.get("https://github.com/")
print(r.from_cache, r.html.links)
```

Or, using the monkey-patch method:
```python
install_cache(session_factory=CachedHTMLSession)
r = requests.get("https://github.com/")
print(r.from_cache, r.html.links)
```
Note that this usage would be more ideal if requests-html could also be used as a mixin.

## Example with internetarchive (#158)
Pretty much the same as above:
```python
import requests
from requests_cache import CacheMixin, install_cache
from internetarchive.session import ArchiveSession

class CachedArchiveSession(CacheMixin, ArchiveSession):
    """Session with features from both CachedSession and ArchiveSession"""
```

## Example with requests-mock (#87)
```python
import requests
from requests_mock import Mocker
from requests_cache import CachedSession

session = CachedSession()
with Mocker(session=session) as m:
    m.get('http://test.com', text='mock_response')
    response = session.get('http://test.com')
    print(response.text)
```

Examples have also been added to the docs.

### CODE REVIEW

**Comment by JWCook** [comment]
@kousu @jeremydouglass If you get the chance, test those changes out for me and let me know if that does the trick. Changes are in the current master branch, not yet released.

**Comment by jeremydouglass** [comment]
Hi @JWCook, this is extremely exciting, and apologies for not seeing this earlier. I'll try to take a look shortly based on my original use case from Jan 2020 in #158

**Comment by JWCook** [comment]
Thanks! Any feedback on that would be appreciated.

**Comment by ddubovoy** [comment]
Something seems to get broken, I tried both "Example with requests-html" and both of them are not working as they should. I'm getting "AttributeError: 'HTMLResponse' object has no attribute 'from_cache'"

I also tried to call install_cache before HTMLSession import and that didn't work too, same error

I also enabled logging DEBUG and caching is working, it is just some problem with the Response inheritance or patching

**Comment by JWCook** [comment]
Thanks for the heads up. You're probably right, something may have changed with the Response class returned by `HTMLSession`. The examples work if you omit the `from_cache` part, which is specific to requests-cache. I'll get that updated in the docs.

```py
from requests_cache import CacheMixin
from requests_html import HTMLSession

class CachedHTMLSession(CacheMixin, HTMLSession):
    """Session with features from both CachedSession and HTMLSession"""

session = CachedHTMLSession()
response = session.get('https://github.com/')
print(response.html.links)
```

An alternative way of checking if a response is cached:
```py
print(session.cache.contains(url='https://github.com/'))
```

Tested with requests-html 0.10.0.

**Comment by ddubovoy** [comment]
Thank you for the quick reply

I figured out why it is not working and the workaround. But I don't even know how it may worked in the first place, as all of the involved code was there before 2021

HTMLSession is hardwired to return HTMLResponse, which is done with the response hook, and that code last changed 7 years. The response hook does update attributes from CachedResponse into HTMLResponse, so if "from_cache" and "is_expired" were attributes, they would be in the final response, like "expires" does

Thank gave me an idea for a workaround, why not add the new attributes to the response with "from_cache" and "is_expired" values. Not exactly pretty but it works. This new hook needs to be executed first in the chain before the other existing hook

```
from requests_cache import CacheMixin
from requests_html import HTMLSession

class CachedHTMLSession(CacheMixin, HTMLSession):
    """Session with features from both CachedSession and HTMLSession"""

def add_cache_properties_as_attributes(response, **kwargs):
    setattr(response, 'is_from_cache', response.from_cache if hasattr(response, 'from_cache') else False)
    setattr(response, 'has_expired', response.is_expired if hasattr(response, 'is_expired') else False)
    return response

session = CachedHTMLSession()

session.hooks['response'].insert(0, add_cache_properties_as_attributes)

r = session.get("https://github.com/")

print(r.is_from_cache, r.has_expired, r.html.links)
```

The alternative method using 

```
session.cache.contains(url='https://github.com/')
```

didn't work for me as it will always returns True after the session.get as the response will be already in the cache, even after the initial http GET

I guess the more elegant solution will be to use some sort of ResponseMixin class similar to CachedHTMLSession, but I don't see any obvious or easy way to do that other than through monkey patching

**Pull request merged**
